[WIP] HH-212093 : Migrated to jakarta dependencies
hhru/consul-java-client pull request #24
Opened 2024-04-04 14:14 UTC by vbazhmin

> [!IMPORTANT] 
> Добавь в описание PR changelog в формате:

- [ ] **version change** : MINOR
- [ ] **description**:

* Updated project dependencies
* Migrated to jakarta dependencies

- [ ] **requires_changes_in_hh** : false
- [ ] **instructions** : N/A

2024-04-04 15:06 UTC, vbazhmin commented
В генерированных классах останутся 

```java
import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.annotation.concurrent.Immutable;
import javax.annotation.concurrent.NotThreadSafe;
import javax.annotation.processing.Generated;
```

2024-04-09 10:19 UTC, rogoza-igor commented
Начал смотреть

2024-04-09 15:30 UTC, rogoza-igor requested changes

2024-04-09 15:30 UTC, rogoza-igor commented on pom.xml
> +        <version>1.57.0.jakarta-rc3</version>
Я вот думаю, может стоит родителем сделать common-pom, чтобы maven-enforcer-plugin вызывался?

2024-04-09 15:30 UTC, rogoza-igor commented on pom.xml
> +                    <source>${java.version}</source>
release включает source и target, так что source можно не добавлять

2024-04-09 15:30 UTC, rogoza-igor commented on src/main/java/ru/hh/consul/model/EventResponse.java
> +@Value.Style(jdkOnly = true, jakarta = true)
Есть еще пачка классов, в которые нужно добавить `@org.immutables.value.Value.Style(jakarta = true)`, чтобы в генерируемых классах не использовались javax аннотации из jsr305
TxError
TxResponse
RaftConfiguration
RaftServer
DnsQuery
Failover
PreparedQuery
QueryId
RaftIndex
ServiceQuery
StoredQuery
Template

2024-04-09 15:30 UTC, rogoza-igor commented on pom.xml
> +            <artifactId>jsr305</artifactId>
Давай выпилим jsr305, раз договорились не использовать его аннотации

2024-04-09 15:30 UTC, rogoza-igor commented on pom.xml
Давай выпилим указание версий для тех зависимостей, которые есть в бутовом помнике

2024-04-09 15:30 UTC, rogoza-igor commented on pom.xml
> +        <retrofit.version>2.11.0</retrofit.version>
Точно стоит апать версию, есть ли в этом необходимость?

2024-04-09 15:30 UTC, rogoza-igor commented on pom.xml
> +        <immutables.version>2.10.1</immutables.version>
Точно стоит апать версию, есть ли в этом необходимость?

2024-04-09 15:33 UTC, rogoza-igor commented
Я б еще предложил не менять местами зависимости/проперти в таком большом количестве, дифф трудно смотреть)

2024-04-10 09:30 UTC, vbazhmin commented on pom.xml
> +        <retrofit.version>2.11.0</retrofit.version>
работает в тандеме с okhttp, думаю стоит

2024-04-10 09:31 UTC, vbazhmin commented on pom.xml
> +        <immutables.version>2.10.1</immutables.version>
да, нужно для `jakarta=true` в аннотациях

2024-04-10 10:05 UTC, vbazhmin commented on src/main/java/ru/hh/consul/model/EventResponse.java
> +@Value.Style(jdkOnly = true, jakarta = true)
Для них они не генерировались, но добавлю на всякий случай, спасибо

2024-04-10 10:05 UTC, vbazhmin commented on pom.xml
> +            <artifactId>jsr305</artifactId>
Выпилил

2024-04-10 10:05 UTC, vbazhmin commented on pom.xml
Перешел на зависимости из нашего common-pom

2024-04-10 10:05 UTC, vbazhmin commented on pom.xml
> +                    <source>${java.version}</source>
Поменял, спасибо

2024-04-10 10:05 UTC, vbazhmin commented on pom.xml
> +        <version>1.57.0.jakarta-rc3</version>
Поменял на common-pom

2024-04-10 10:08 UTC, rogoza-igor commented on src/main/java/ru/hh/consul/model/EventResponse.java
> +@Value.Style(jdkOnly = true, jakarta = true)
я в таргете чекал, щас генерятся)

2024-04-10 10:26 UTC, vbazhmin commented on src/main/java/ru/hh/consul/model/EventResponse.java
> +@Value.Style(jdkOnly = true, jakarta = true)
странно, специально делал билд , может просмотрел ...

2024-04-10 11:09 UTC, rogoza-igor commented on pom.xml
> +        <retrofit.version>2.11.0</retrofit.version>
Договорились попробовать оставить retrofit 2.9.0, а okhttp апнуть до 4.10.0

2024-04-10 14:26 UTC, vbazhmin commented
<img width="903" alt="image" src="https://github.com/hhru/consul-java-client/assets/111894721/5e2b7002-c6d6-4d5a-b3bb-094a240961c7">

2024-04-10 14:30 UTC, rogoza-igor commented on pom.xml
> +        <version>1.57.0.jakarta-rc3</version>
Договорились наследоваться от public-pom'а и просто локально прогнать энфорсер (после этого выпилить его)

2024-04-10 14:30 UTC, vbazhmin commented on pom.xml
> +        <version>1.57.0.jakarta-rc3</version>
https://github.com/hhru/consul-java-client/pull/24#issuecomment-2047705165

2024-04-10 14:31 UTC, vbazhmin commented
Removed maven-enforcer plugin

2024-04-10 14:31 UTC, rogoza-igor approved these changes

2024-04-10 14:39 UTC, vbazhmin commented
Squashed commits and added release commits

2024-04-10 14:39 UTC, merged

2024-04-10 14:40 UTC, vbazhmin commented
Tested on applicant-services via redis-client library

![image](https://github.com/hhru/consul-java-client/assets/111894721/1e891c36-ffd7-4449-b5dc-f0bdb312d272)